# Generated by Django 4.1.7 on 2023-03-29 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.student",
                to_field="usn",
                verbose_name="student",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="usn",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
