# Generated by Django 4.1.7 on 2023-03-29 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_attendance_student_alter_student_usn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.student",
                verbose_name="student",
            ),
        ),
    ]
