# Generated by Django 4.1.7 on 2023-03-30 03:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_attendance_student"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
