# Generated by Django 4.1.7 on 2023-03-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_attendance_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="image",
        ),
        migrations.AddField(
            model_name="student",
            name="api.models",
            field=models.ImageField(null=True, upload_to="db_path/"),
        ),
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
