# Generated by Django 4.1.7 on 2023-03-30 03:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_delete_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="image",
            field=models.ImageField(null=True, upload_to=api.models.renameImagePath),
        ),
    ]
