# Generated by Django 4.1.7 on 2023-03-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_student_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
